CREATE TABLE NEWS
(
  NEWS_ID NUMBER NOT NULL
, SHORT_TEXT VARCHAR2(100 BYTE) NOT NULL
, FULL_TEXT VARCHAR2(2000 BYTE) NOT NULL
, TITLE VARCHAR2(30 BYTE) NOT NULL
, CREATION_DATE TIMESTAMP(6) NOT NULL
, MODIFICATION_DATE DATE NOT NULL
, CONSTRAINT NEWS_PK PRIMARY KEY
  (
    NEWS_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX NEWS_PK ON NEWS (NEWS_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;
/
CREATE TABLE AUTHOR
(
  AUTHOR_ID NUMBER NOT NULL
, NAME VARCHAR2(30 BYTE) NOT NULL
, CONSTRAINT AUTHOR_PK PRIMARY KEY
  (
    AUTHOR_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX AUTHOR_PK ON AUTHOR (AUTHOR_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;
/
CREATE TABLE COMMENTS
(
  COMMENT_ID NUMBER NOT NULL
, COMMENT_TEXT VARCHAR2(100 BYTE) NOT NULL
, CREATION_DATE TIMESTAMP(6) NOT NULL
, NEWS_ID NUMBER NOT NULL
, CONSTRAINT COMMENTS_PK PRIMARY KEY
  (
    COMMENT_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX COMMENTS_PK ON COMMENTS (COMMENT_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_FK1 FOREIGN KEY
(
  NEWS_ID
)
REFERENCES NEWS
(
  NEWS_ID
)
ON DELETE CASCADE ENABLE;
/
CREATE TABLE TAG
(
  TAG_ID NUMBER NOT NULL
, TAG_NAME VARCHAR2(30 BYTE) NOT NULL
, CONSTRAINT TAG_PK PRIMARY KEY
  (
    TAG_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX TAG_PK ON TAG (TAG_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;
/
CREATE TABLE NEWS_AUTHOR
(
  NEWS_AUTHOR_ID NUMBER NOT NULL
, NEWS_ID NUMBER NOT NULL
, AUTHOR_ID NUMBER NOT NULL
, CONSTRAINT NEWS_AUTHOR_PK PRIMARY KEY
  (
    NEWS_AUTHOR_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX NEWS_AUTHOR_PK ON NEWS_AUTHOR (NEWS_AUTHOR_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;

ALTER TABLE NEWS_AUTHOR
ADD CONSTRAINT NEWS_AUTHOR_FK1 FOREIGN KEY
(
  NEWS_ID
)
REFERENCES NEWS
(
  NEWS_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE NEWS_AUTHOR
ADD CONSTRAINT NEWS_AUTHOR_FK2 FOREIGN KEY
(
  AUTHOR_ID
)
REFERENCES AUTHOR
(
  AUTHOR_ID
)
ON DELETE CASCADE ENABLE;
/
CREATE TABLE NEWS_TAG
(
  NEWS_TAG_ID NUMBER NOT NULL
, NEWS_ID NUMBER NOT NULL
, TAG_ID NUMBER NOT NULL
, CONSTRAINT NEWS_TAG_PK PRIMARY KEY
  (
    NEWS_TAG_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX NEWS_TAG_PK ON NEWS_TAG (NEWS_TAG_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;

ALTER TABLE NEWS_TAG
ADD CONSTRAINT NEWS_TAG_FK1 FOREIGN KEY
(
  NEWS_ID
)
REFERENCES NEWS
(
  NEWS_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE NEWS_TAG
ADD CONSTRAINT NEWS_TAG_FK2 FOREIGN KEY
(
  TAG_ID
)
REFERENCES TAG
(
  TAG_ID
)
ON DELETE CASCADE ENABLE;


/
CREATE TABLE VISITOR
(
  USER_ID NUMBER(20, 0) NOT NULL
, USER_NAME NVARCHAR2(50) NOT NULL
, LOGIN VARCHAR2(30 BYTE) NOT NULL
, PASSWORD VARCHAR2(30 BYTE) NOT NULL
, CONSTRAINT TABLE1_PK PRIMARY KEY
  (
    USER_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX TABLE1_PK ON VISITOR (USER_ID ASC)
      LOGGING
      TABLESPACE USERS
      PCTFREE 10
      INITRANS 2
      STORAGE
      (
        INITIAL 65536
        NEXT 1048576
        MINEXTENTS 1
        MAXEXTENTS UNLIMITED
        BUFFER_POOL DEFAULT
      )
      NOPARALLEL
  )
  ENABLE
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;
/

CREATE TABLE ROLES
(
  ROLE_NAME VARCHAR2(50 BYTE) NOT NULL
, USER_ID NUMBER(20, 0) NOT NULL
)
LOGGING
TABLESPACE USERS
PCTFREE 10
INITRANS 1
STORAGE
(
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS UNLIMITED
  BUFFER_POOL DEFAULT
)
NOCOMPRESS
NOPARALLEL;

ALTER TABLE ROLES
ADD CONSTRAINT ROLES_FK1 FOREIGN KEY
(
  USER_ID
)
REFERENCES VISITOR
(
  USER_ID
)
ENABLE;
/